Updated category model tests
josue-avila/OTS_ATP pull request #2
Opened 2021-01-29 21:09 UTC by mblopes

Criados testes e validators para model de category

2021-01-29 21:11 UTC, josue-avila requested changes

2021-01-29 21:11 UTC, josue-avila commented on .gitignore
> -
Quando compartilhar comigo vou ter que colocar isso aqui de novo ):

2021-02-01 11:37 UTC, mblopes commented on .gitignore
> -
Não entendi como, mas não fui eu que removi isso aí kkkkkk

2021-02-01 11:46 UTC, lucianahb approved these changes

2021-02-01 12:04 UTC, josue-avila approved these changes

2021-02-01 12:23 UTC, merged